config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # get 'courts/index'
  # get 'courts/show'
  devise_for :users
  root 'courts#index'
  resources :courts, only: [:index, :show]
  resources :games

  get 'games/:id/set_opponent', to: 'games#set_opponent'
  put 'games/:id/set_opponent', to: 'games#set_opponent'
  post 'games/:id/set_opponent', to: 'games#set_opponent', as: 'set_opponent'

  get 'games/:id/set_scorekeeper', to: 'games#set_scorekeeper'
  put 'games/:id/set_scorekeeper', to: 'games#set_scorekeeper'
  post 'games/:id/set_scorekeeper', to: 'games#set_scorekeeper', as: 'set_scorekeeper'
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
class Court < ApplicationRecord
    has_many :games
    validates :name, :address, :city, :state, presence: true
    geocoded_by :full_address
    after_validation :geocode

    def full_address
        [address, city, state].join(', ')
    end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :court
  belongs_to :score_keeper, class_name: "User", optional: true
  belongs_to :opponent, class_name: "User",  optional: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :nickname, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games
  has_many :games_where_opponent, class_name: "Game",  foreign_key: "opponent_id"
  has_many :games_where_keeper, class_name: "Game",  foreign_key: "score_keeper_id"

  def self.get_nickname(user_id)
    User.find(user_id).nickname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
        devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
    end
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController

  def index
    respond_to do |format|
      format.html do
        @coordinates = request.location.coordinates.reverse
        @coordinates = [0.0, 0.0] if @coordinates.empty?
      end
      format.json do
        @courts = Court.all
        render json:  {
                        type: "FeatureCollection",
                        features: @courts.map do |court|
                          {
                            type: "Feature",
                            geometry: {
                              type: "Point",
                              coordinates: [court.longitude, court.latitude]
                            },
                            properties: {
                              name: court.name,
                              id: court.id
                            }
                          }
                        end
                      }
      end
    end
  end

  def show
    @court = Court.find(params[:id])
    @games = Game.where(court_id: @court).order('id ASC')
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :set_game, only: [:show, :update, :set_opponent, :set_scorekeeper]
    skip_before_action :verify_authenticity_token

    def show
      @court = @game.court
      @user = @game.user
      @score_keeper = @game.score_keeper || { nickname: "No scorekeeper", id: 0}
      @opponent = @game.opponent || { nickname: "TBD" }
    end

    def update
      @game.update(game_params)
      render json: @game
    end

    def set_opponent 
      @game.opponent = current_user
      @game.save 
       #@game.update_attribute(:opponent, current_user.id)
      redirect_to @game
    end 

    def set_scorekeeper 
      @game.score_keeper = current_user
      @game.save
      redirect_to @game
    end 

    def create
      @game = current_user.games.new(court_id: params[:court_id])
      if @game.save
        redirect_to @game,
          notice: 'game was successfully created.'
      else
        redirect_to Court.find(params[:court_id]),
          alert: "Could not create game: #{@games.errors.full_messages.join(', ')}"
      end
    end

    private

    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:user_points, :opponent_points)
    end
  
  end
  

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/views/courts/index.html.erb
<h2 class="text-center">Choose Your Court!</h1>

<%= react_component 'Map', props: { coordinates: @coordinates} %>

app/views/courts/show.html.erb
<h1 class="text-center"><%= @court.name %> </h1>
<h3 class="text-center"><%= "#{@court.address}, #{@court.city}, #{@court.state}" %> </h1>
<div class="text-center pb-2">
        <%= button_to "Create Game", {controller: "games", action: "create", court_id: @court.id }, class: 'btn btn-primary' %>
</div>
<table class="table">
    <thead >
        <th></th>
        <th class="text-center">Player1</th>
        <th class="text-center">Opponent</th>
        <th class="text-center">Ref</th>
    </thead> 
    <tbody>
        <% @games.each do |game| %>
            <tr>
                <td class="text-center">
                    <%= link_to game do%>
                        <%= image_tag('BasketBall.png', width: 20) %>
                    <% end %>
                </td>
                <td class="text-center"><%= game.user.nickname %></td>
                <% if game.opponent.nil? %>
                    <td class="text-center"><%= render 'games/set_opponent', game: game %></td>
                <% else %>
                     <td class="text-center"><%= game.opponent&.nickname %></td>
                <% end %>
                <% if game.score_keeper.nil? %>
                    <td class="text-center"><%= render 'games/set_scorekeeper', game: game %></td>
                <% else %>
                     <td class="text-center"><%= game.score_keeper&.nickname %></td>
                <% end %>
                
            </tr>
        <% end %>
    </tbody>
</table>

app/views/games/_set_opponent.html.erb
<%= form_tag set_opponent_path(:id => game.id) do %>
    <%= submit_tag("Join", class: "btn btn-primary") %>
<% end  %>

app/views/games/_set_scorekeeper.html.erb
<%= form_tag set_scorekeeper_path(:id => game.id) do %>
    <%= submit_tag("Join", class: "btn btn-primary") %>
<% end  %>

app/views/games/show.html.erb
<%= react_component 'Game', 
    props: {
        game: @game,
        user: @user,
        opponent: @opponent,
        score_keeper: @score_keeper,
        current_user: current_user
    } %>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>1v1 STREET BALL</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.css' rel='stylesheet' />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to "1v1 STREET BALL", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Courts", courts_path, class: "nav-link" %>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class=nav-item>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>